# Generated by Django 3.0.3 on 2020-02-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('nota_fiscal', models.IntegerField()),
                ('transportadora', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=8)),
            ],
        ),
    ]
