# Generated by Django 3.0.3 on 2020-02-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
