# Generated by Django 3.0.3 on 2020-02-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_auto_20200212_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='nota_fiscal',
            field=models.CharField(max_length=7),
        ),
    ]
